version: "2.2"
services:

  gestionbloc:
    container_name: gestionbloc
    build:
      context: ./
      dockerfile: Docker-club
    ports:
      - "8082:8082"
    hostname: 127.0.0.1
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "gestionbloc"
    depends_on:
      - Eureka

  gestionchambre:
    container_name: gestionchambre
    build:
      context: ./
      dockerfile: Docker-chambre
    ports:
      - "8085:8085"
    hostname: 127.0.0.1
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "gestionchambre"
    depends_on:
      - Eureka
  Eureka:
    container_name: serviceregistry
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/